add new attack to dummy and make the spamton shop thingy have 0 cost
darkplace-dr/Dark-Place pull request #636
Opened 2024-04-07 08:56 UTC by emir4169

funy

2024-04-07 13:52 UTC, Dobby233Liu reviewed
I think the line endings in scripts/world/maps/room1/data.lua and corrspending tmx got messed up

2024-04-07 14:02 UTC, Dobby233Liu requested changes
Not to mention we already have a room2, IDK how you handled it, it's hard to tell from the messed up diff

2024-04-07 14:02 UTC, Dobby233Liu commented on libraries/dash_soul/lib.json
> +    "engineVersion": "0.9.0-dev"
```suggestion
    "version": "v1.0.0",
    "engineVersion": "v0.9.0-dev"
```

2024-04-07 15:21 UTC, emir4169 commented on libraries/dash_soul/lib.json
> +    "engineVersion": "0.9.0-dev"
wait we already have one???

2024-04-07 15:22 UTC, emir4169 commented
(also please tell me if you know how to fix the great dash issue of not dashing)

2024-04-07 15:49 UTC, Dobby233Liu commented
> (also please tell me if you know how to fix the great dash issue of not dashing)

Probably requires overwriting the doMovement function entirely. Makes this warrant becoming a separate object.

2024-04-07 15:54 UTC, Dobby233Liu requested changes

2024-04-07 15:54 UTC, Dobby233Liu commented on scripts/world/maps/room1/data.lua
```bash
unix2dos scripts/world/maps/room1/data.lua
```

2024-04-07 15:54 UTC, Dobby233Liu commented on scripts/world/maps/room1/room1.tmx
```bash
unix2dos scripts/world/maps/room1/room1.tmx
```

2024-04-07 15:55 UTC, Dobby233Liu commented on scripts/world/maps/room1/room1.tmx
If Tiled undos this it would be tragic

2024-04-07 16:02 UTC, Dobby233Liu commented
> it's hard to tell from the messed up diff

Actually hiding whitespace changes did wonders here, aside of noise caused by inconsistent Tiled version, it seems you just touched some collision and added a loading zone for room2, so you didn't handle it at all. Suggest moving what you have in your room2 over to our room2 then remove the former

> (also please tell me if you know how to fix the great dash issue of not dashing)
I think it has something to do with the fact we already have a Soul hook file

2024-04-07 17:44 UTC, emir4169 commented
> > it's hard to tell from the messed up diff
> 
> Actually hiding whitespace changes did wonders here, aside from noise caused by inconsistent Tiled version, it seems you just touched some collision and added a loading zone for room2, so you didn't handle it at all. Suggest moving what you have in your room2 over to our room2, then remove the former
i shrimply just erased my room2 out of existence
> > (also please tell me if you know how to fix the great dash issue of not dashing)
> 
> I think it has something to do with the fact we already have a Soul hook file. We always had trouble with stuff like this
put the code in the soul hook file, doesnt seem to work still

2024-06-02 15:18 UTC, JustAnotherRandomGithubUser commented
Closed due to a lack of activity.

2024-06-02 15:18 UTC, closed without merging